pub mod dnf;
pub mod oci;

use crate::config::Manifest;
use color_eyre::{Result, eyre::bail};
use std::path::{Path, PathBuf};

pub trait RootBuilder {
	fn build(&self, chroot: &Path, manifest: &Manifest) -> Result<TreeOutput>;
}

/// The kind of tree a [`RootBuilder`] produced.
///
/// Most builders produce a plain root filesystem. The bootc builder in its
/// `ostree` layout instead produces an OSTree *sysroot*: a directory holding an
/// OSTree repository plus a deployed, bootable commit. The two are not
/// interchangeable
/// 
/// a sysroot's content lives under
/// `ostree/deploy/<stateroot>/deploy/<checksum>.0`, and boot metadata is
/// generated by ostree rather than by us so phases must branch on this
/// rather than treat every output as a rootfs.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum TreeOutput {
	// tar stream, unused atm
	Tarball(PathBuf),
	/// A plain root filesystem.
	Directory(PathBuf),
	/// An OSTree sysroot containing a repository and a bootable deployment.
	OstreeSysroot {
		/// The sysroot root, i.e. the directory containing `ostree/repo`.
		sysroot: PathBuf,
		/// The stateroot (ostree `--os`) the deployment lives under.
		stateroot: String,
	},
}

impl TreeOutput {
	/// The path that should be treated as the root filesystem for this output.
	///
	/// For a plain directory this is the directory itself. For a sysroot this is
	/// the *deployment* root, so that callers which only need to read or modify
	/// files (bootloader copying, dracut, inspection) do not have to know about
	/// the ostree layout.
	pub fn rootfs(&self) -> Result<PathBuf> {
		match self {
			Self::Directory(path) => Ok(path.clone()),
			Self::OstreeSysroot { sysroot, stateroot } => {
				let deploy_dir = sysroot.join("ostree/deploy").join(stateroot).join("deploy");
				let deployment = find_deployment(&deploy_dir)?;
				Ok(deployment)
			},
			Self::Tarball(_) => {
				bail!("Tarball output has no root filesystem; this code path is unimplemented")
			},
		}
	}

	/// The directory that should be squashed into the live image.
	///
	/// This is deliberately *not* the same as [`Self::rootfs`]: for a sysroot the
	/// whole sysroot must ship, because the repository it contains is what makes
	/// the deployment bootable.
	pub fn squash_root(&self) -> PathBuf {
		match self {
			Self::Directory(path) => path.clone(),
			Self::OstreeSysroot { sysroot, .. } => sysroot.clone(),
			Self::Tarball(path) => path.clone(),
		}
	}

	/// Whether this output is an OSTree sysroot.
	pub fn is_sysroot(&self) -> bool {
		matches!(self, Self::OstreeSysroot { .. })
	}
}

/// Find the (single) deployment directory under a stateroot's `deploy` dir.
///
/// Deployments are named `<commit checksum>.0`; we pick the first one, which is
/// the booted/default deployment because we only ever deploy a single commit.
pub fn find_deployment(deploy_dir: &Path) -> Result<PathBuf> {
	let entries = std::fs::read_dir(deploy_dir).map_err(|e| {
		color_eyre::eyre::eyre!("Reading deployments from {}: {e}", deploy_dir.display())
	})?;

	for entry in entries.flatten() {
		let path = entry.path();
		let name = entry.file_name();
		let name = name.to_string_lossy();
		// Ignore the `.origin` sidecar files ostree writes next to deployments.
		if path.is_dir() && name.ends_with(".0") {
			return Ok(path);
		}
	}

	bail!("No deployment found under {}", deploy_dir.display())
}
