[package]
name = "katsu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
log = "0.4.17"
pretty_env_logger = "0.4.0"
in-container = "1.1.0"
sudo = "0.6.0"
