[package]
name = "katsu"
version = "0.1.0"
edition = "2021"
authors = [
    "Fyra Labs",
    "Pornpipat Popum <cappy@fyralabs.com>",
    "Madomado <mado@fyralabs.com>",
    "Lleyton Gray <lleyton@fyralabs.com>",
]
description = "A rusty tool to build OS images"
license = "MIT"
categories = ["system", "utilities"]
keywords = ["build", "image", "os", "linux", "chroot", "container"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
in-container = "1.1.0"
sudo = "0.6.0"
tracing = "0.1.37"
color-eyre = "0.6.2"
tracing-subscriber = { version = "0.3.16", features = [
    "env-filter",
    "tracing-log",
] }
serde_derive = "1.0.152"
serde = "1.0.152"
smartstring = { version = "1.0.1", features = ["serde"] }
tracing-error = "0.2.0"
regex = { version = "1.8.4", features = ["unicode-case"] }
glob = "0.3.1"
cmd_lib = "1.3.0"
serde_yaml = "0.9.25"
dotenvy = "0.15.7"
gpt = "3.1.0"
block-utils = "0.11.1"
tera = "1"
merge-struct = "0.1.0"
clap = { version = "4.4.6", features = ["derive", "env"] }
