ARG DERIVE_FROM
FROM registry.fedoraproject.org/fedora:41 AS bootloader_base
# HACK: We copy GRUB2 and shim from Fedora, because CentOS' GRUB2 is kinda wonky

# todo: aarch64 hack
RUN dnf install -y grub2 grub2-efi grub2-tools grub2-tools-extra xorriso shim dosfstools grub2-efi-x64-modules grub2-efi-x64-cdboot grub2-efi-x64

FROM ${DERIVE_FROM}

# Install the necessary packages
RUN dnf install -y kernel dracut dracut-live grub2-tools grub2-common grub2-pc-modules grub2-efi-x64 shim-x64 && \
    dnf clean all

COPY --from=bootloader_base /boot/efi /boot/efi
COPY --from=bootloader_base /boot/grub2 /boot/grub2

# yeah thats pretty much it