#!/bin/sh
# Prepare the live media for a native composefs deployment.
#
# Unlike the OSTree path, root selection is not our job: bootc's own
# `bootc-root-setup.service` reads `composefs=<D>` and assembles the root from
# `/sysroot/composefs`. We only have to expose the ISO payload as `/sysroot` and
# let bootc take over. `/sysroot` must not be an overlay: bootc mounts the
# composefs image itself, and the kernel refuses an EROFS image whose backing
# file lives on overlayfs (`ENOTBLK`).
. /lib/dracut-lib.sh

fail() {
    echo "katsu-composefs-live: $*" >&2
    exit 1
}

label=$(getarg rd.katsu.label=) || fail 'Missing rd.katsu.label'
[ -n "$label" ] || fail 'Empty rd.katsu.label'

mkdir -p /run/initramfs/live /run/katsu/ro
if getargbool 0 rd.live.check; then
    checkisomd5 --verbose "/dev/disk/by-label/$label" || fail 'ISO media check failed'
fi
mount -t iso9660 -o ro "/dev/disk/by-label/$label" /run/initramfs/live \
    || fail "Cannot mount ISO with label $label"
ln -s "/dev/disk/by-label/$label" /run/initramfs/livedev

image=/run/initramfs/live/LiveOS/rootfs.img
[ -f "$image" ] || fail "Root image not found: $image"

# The payload is a GPT disk, not a bare filesystem: bootc looks for an ESP among
# the backing devices of everything it mounts, and only a partitioned disk can
# expose one. Its root filesystem is partition 3 (ESP, XBOOTLDR, root).
#
# The loop is deliberately *not* attached read-only. bootc's `Storage::new`,
# which every command including `bootc status` goes through, mounts the ESP with a
# plain `mount(2)` and no `MS_RDONLY`; the kernel then refuses with `EPERM` if the
# loop is read-only, and `bootc status` fails with `Mounting /dev/loopNp1:
# Permission denied`. `mount(8)` hides this by silently downgrading to a
# read-only mount, but bootc calls the syscall directly. Nothing is written in
# practice: the backing file lives on the read-only ISO, so writes would be
# rejected by the medium.
loop=$(losetup --show -P --find "$image") || fail 'Cannot attach live root image'
[ -b "${loop}p3" ] || fail "No root partition in $image (expected a GPT payload)"
mount -o ro "${loop}p3" /run/katsu/ro || fail 'Cannot mount live root partition'

[ -d /run/katsu/ro/composefs ] || fail 'Live image contains no composefs repository'
# bootc-root-setup opens the deployment state even when no /etc or /var mount is
# configured, so its absence is fatal later and worth catching here.
boot_digest=$(getarg composefs=)
boot_digest=${boot_digest#\?}
[ -d "/run/katsu/ro/state/deploy/$boot_digest" ] \
    || fail "Live image has no state for deployment $boot_digest"

# sysroot.mount binds this payload onto /sysroot; see the unit generated by
# stage_composefs_live. Mounts created from read-only media must survive
# switch-root teardown.
need_shutdown
echo "katsu-composefs-live: prepared composefs media with $boot_digest"