use super::{Bootloader, GRUB_PREPEND_COMMENT, OstreeDeployment};
use crate::{
	builder::{BOOTIMGS, ISO_TREE},
	config::Manifest,
	util::loopdev_with_file,
};
use color_eyre::{Result, eyre::bail};
use std::{fs, os::unix::fs::symlink, path::Path};
use tracing::{debug, info, info_span, trace, warn};

/// The boot parameters a GRUB config needs, grouped so the template writer stays
/// readable as boot options grow.
struct GrubBootParams<'a> {
	volid: &'a str,
	distro: &'a str,
	vmlinuz: &'a str,
	initramfs: &'a str,
	kernel_cmdline: &'a str,
}

impl Bootloader {
	pub(super) fn cp_grub(
		&self, manifest: &Manifest, chroot: &Path, workspace: &Path,
		ostree: Option<&OstreeDeployment>,
	) -> Result<()> {
		let iso_tree = workspace.join(ISO_TREE);
		let boot_imgs_dir = workspace.join(BOOTIMGS);

		fs::create_dir_all(&boot_imgs_dir)?;
		if self.get_arch(manifest) == "x86_64" {
			info!("Copying GRUB hybrid boot image");
			let hybrid_img = chroot.join("usr/lib/grub/i386-pc/boot_hybrid.img");
			trace!(?hybrid_img, "Source hybrid boot image location");
			let dest = boot_imgs_dir.join("boot_hybrid.img");
			trace!(?dest, "Destination hybrid boot image location");
			if !hybrid_img.exists() {
				warn!("Hybrid boot image not found at expected location");
			}
			fs::copy(&hybrid_img, &dest)?;
			debug!("Successfully copied hybrid boot image");
		}

		self.create_grub_directories(&iso_tree, &boot_imgs_dir)?;

		let kernel_cmdline = manifest.kernel_cmdline.as_deref().unwrap_or("");
		let volid = manifest.get_volid();
		let distro = manifest.distro.as_deref().unwrap_or("Linux");

		let (vmlinuz, initramfs) =
			self.copy_kernel_and_initramfs(chroot, &boot_imgs_dir, &iso_tree)?;

		self.generate_grub_config(
			&iso_tree,
			&GrubBootParams {
				volid: &volid,
				distro,
				vmlinuz: &vmlinuz,
				initramfs: &initramfs,
				kernel_cmdline,
			},
			ostree,
		)?;
		self.setup_efi_boot_files(manifest, &iso_tree)?;
		self.generate_grub_images(chroot, &iso_tree, manifest)?;
		self.mkefiboot(workspace, manifest)?;

		Ok(())
	}

	fn create_grub_directories(&self, iso_tree: &Path, boot_imgs_dir: &Path) -> Result<()> {
		fs::create_dir_all(iso_tree)?;
		fs::create_dir_all(boot_imgs_dir)?;
		Ok(())
	}

	fn copy_kernel_and_initramfs(
		&self, chroot: &Path, boot_imgs_dir: &Path, iso_tree: &Path,
	) -> Result<(String, String)> {
		let (vmlinuz, initramfs) = self.cp_vmlinuz_initramfs(chroot, boot_imgs_dir, true)?;

		let iso_boot = iso_tree.join("boot");
		let chroot_boot = if chroot.join("usr/lib/ostree-boot").exists() {
			info!("Detected ostree-boot structure");
			chroot.join("usr/lib/ostree-boot")
		} else {
			chroot.join("boot")
		};
		// HACK: detect ostree-boot to avoid copying wrong files
		let ostree_boot = chroot_boot.ends_with("ostree-boot");

		// Keep the live initramfs generated by the dracut phase.
		fs::create_dir_all(&iso_boot)?;

		let grub_dest = iso_boot.join("grub");
		let grub2_src = chroot_boot.join("grub2");
		let grub_src = chroot_boot.join("grub");
		let grub_lib_dir = chroot.join("usr/lib/grub");
		let _ = fs::remove_dir_all(&grub_dest);
		if grub2_src.exists() {
			Self::copy_dir(&grub2_src, &grub_dest)?;
		} else if grub_src.exists() {
			Self::copy_dir(&grub_src, &grub_dest)?;
		} else if grub_lib_dir.exists() {
			warn!(
				"Grub directory not found in boot directory, but usr/lib/grub exists. Copying from there."
			);
			Self::copy_dir(&grub_lib_dir, &grub_dest)?;
			// Copy fonts to proper font directory
			let fonts_src = chroot.join("usr/share/grub");
			if fonts_src.exists() {
				let fonts_dest = grub_dest.join("fonts");
				Self::copy_dir(&fonts_src, &fonts_dest)?;
			} else {
				warn!("No grub fonts directory found in {}", fonts_src.display());
			}
		} else {
			bail!("Missing grub directory in {}", chroot_boot.display());
		}

		let efi_dest = iso_boot.join("efi");
		let _ = fs::remove_dir_all(&efi_dest);
		info_span!("Copying EFI boot files").in_scope(|| -> Result<()> {
			info!(?efi_dest, "Copying EFI boot files");
			Self::copy_efi_payload(chroot, &chroot_boot, &efi_dest, ostree_boot)
		})?;

		fs::copy(boot_imgs_dir.join("boot").join(&vmlinuz), iso_boot.join(&vmlinuz))?;

		// The dracut phase writes the live-capable initramfs straight into the ISO
		// tree, so only fall back to the staged copy when nothing is there yet.
		if iso_boot.join("initramfs.img").exists() {
			debug!("Keeping the initramfs produced by the dracut phase");
		} else {
			fs::copy(boot_imgs_dir.join("boot").join(&initramfs), iso_boot.join("initramfs.img"))?;
		}

		Ok((vmlinuz, "initramfs.img".to_string()))
	}

	/// Locates and copies the EFI payload into the ISO tree's `/boot/efi`.
	fn copy_efi_payload(
		chroot: &Path, chroot_boot: &Path, efi_dest: &Path, ostree_boot: bool,
	) -> Result<()> {
		// bootupd path
		let usr_lib_efi = chroot.join("usr/lib/efi");
		if usr_lib_efi.join("EFI").exists() || Self::usr_efi_has_components(&usr_lib_efi) {
			info!(?usr_lib_efi, "Copying EFI boot files from usr/lib/efi");
			return Self::copy_usr_lib_efi(&usr_lib_efi, &efi_dest.join("EFI"));
		}

		// Legacy `<boot>/efi` tree, when it still has content.
		let efi_src = chroot_boot.join("efi");
		let efi_src_efi = efi_src.join("EFI");
		if Self::dir_has_entries(&efi_src_efi)? {
			info!(?efi_src, "Copying EFI boot files from boot tree");
			return Self::copy_dir(&efi_src, efi_dest);
		}

		// Some images keep a populated /boot/efi (vfat ESP mounted during build).
		let boot_efi = chroot.join("boot/efi");
		if Self::dir_has_entries(&boot_efi.join("EFI"))? {
			info!(?boot_efi, "Copying EFI boot files from /boot/efi");
			return Self::copy_dir(&boot_efi, efi_dest);
		}

		if ostree_boot {
			bail!(
				"No EFI payload found: {} has no EFI directory and {} is empty",
				usr_lib_efi.display(),
				efi_src.display()
			);
		}
		warn!("No EFI directory found in {}", chroot_boot.display());
		Ok(())
	}

	/// Copies every `EFI` directory found at `usr/lib/efi/<name>/<version>/EFI`,
	/// mirroring bootupd's `get_efi_component_from_usr()` walk.
	fn copy_usr_lib_efi(usr_lib_efi: &Path, efi_dest: &Path) -> Result<()> {
		fs::create_dir_all(efi_dest)?;

		for entry in fs::read_dir(usr_lib_efi)? {
			let entry = entry?;
			let entry_path = entry.path();
			if !entry_path.is_dir() {
				continue;
			}
			for version_entry in fs::read_dir(&entry_path)? {
				let version_path = version_entry?.path();
				// `usr/lib/efi/<name>/<version>/EFI`; ignore anything else.
				let efi_subsrc = version_path.join("EFI");
				if !efi_subsrc.exists() {
					continue;
				}
				debug!(?efi_subsrc, ?efi_dest, "Copying EFI subdirectory from usr/lib/efi");
				Self::copy_dir(&efi_subsrc, efi_dest)?;
			}
		}

		if !Self::dir_has_entries(efi_dest)? {
			bail!("No EFI components found under {}", usr_lib_efi.display());
		}
		Ok(())
	}

	/// True when any `usr/lib/efi/<name>/<version>/EFI` directory exists.
	fn usr_efi_has_components(usr_lib_efi: &Path) -> bool {
		let Ok(entries) = fs::read_dir(usr_lib_efi) else {
			return false;
		};
		entries.flatten().any(|entry| {
			let path = entry.path();
			if !path.is_dir() {
				return false;
			}
			fs::read_dir(&path)
				.map(|versions| versions.flatten().any(|v| v.path().join("EFI").exists()))
				.unwrap_or(false)
		})
	}

	/// True when the directory exists and contains at least one entry.
	fn dir_has_entries(dir: &Path) -> Result<bool> {
		if !dir.is_dir() {
			return Ok(false);
		}
		Ok(fs::read_dir(dir)?.next().is_some())
	}

	fn copy_dir(src: &Path, dest: &Path) -> Result<()> {
		if !src.exists() {
			bail!("Source directory {} does not exist", src.display());
		}
		if dest.exists() {
			// Actually just append files instead of removing existing directory
			// fs::remove_dir_all(dest)?;
		}
		fs::create_dir_all(dest)?;

		for entry in fs::read_dir(src)? {
			let entry = entry?;
			let entry_path = entry.path();
			let dest_path = dest.join(entry.file_name());
			let file_type = fs::symlink_metadata(&entry_path)?.file_type();
			if file_type.is_dir() {
				Self::copy_dir(&entry_path, &dest_path)?;
			} else if file_type.is_file() {
				fs::copy(&entry_path, &dest_path)?;
			} else if file_type.is_symlink() {
				let target = fs::read_link(&entry_path)?;
				symlink(target, &dest_path)?;
			}
		}

		Ok(())
	}

	fn generate_grub_config(
		&self, iso_tree: &Path, boot: &GrubBootParams<'_>, ostree: Option<&OstreeDeployment>,
	) -> Result<()> {
		// When booting an OSTree deployment the initramfs needs to be told where
		// the deployment lives; without this it cannot find the root filesystem.
		let ostree_karg = ostree.map(|o| o.karg.clone()).unwrap_or_default();
		if !ostree_karg.is_empty() {
			info!(karg = %ostree_karg, "Booting an OSTree deployment");
		}

		crate::tpl!(
			"grub.cfg.tera" => {
				GRUB_PREPEND_COMMENT,
				volid: boot.volid.to_string(),
				distro: boot.distro.to_string(),
				vmlinuz: boot.vmlinuz.to_string(),
				initramfs: boot.initramfs.to_string(),
				cmd: boot.kernel_cmdline.to_string(),
				ostree: ostree_karg
			} => iso_tree.join("boot/grub/grub.cfg")
		);

		Ok(())
	}

	/// Preserve the EFI vendor layout, including fallback CSVs and GRUB configs.
	fn setup_efi_boot_files(&self, manifest: &Manifest, iso_tree: &Path) -> Result<()> {
		let arch_short_upper = self.get_arch_short(manifest).to_uppercase();

		let efi_root = iso_tree.join("boot/efi/EFI");
		let boot_out = iso_tree.join("EFI/BOOT");
		fs::create_dir_all(&boot_out)?;

		let boot_src = efi_root.join("BOOT");
		if !Self::dir_has_entries(&boot_src)? {
			bail!(
				"No EFI boot payload found at {}; the image is missing shim's removable-media loader",
				boot_src.display()
			);
		}
		debug!(?boot_src, ?boot_out, "Copying shim removable-media payload");
		Self::copy_dir(&boot_src, &boot_out)?;

		let mut vendor_copied = false;
		for vendor in ["fedora", "centos", "redhat"] {
			let src = efi_root.join(vendor);
			if !Self::dir_has_entries(&src)? {
				continue;
			}
			let dest = iso_tree.join("EFI").join(vendor);
			debug!(?src, ?dest, "Copying EFI vendor directory");
			Self::copy_dir(&src, &dest)?;
			// Packaged GRUB can use a vendor prefix rather than EFI/BOOT.
			fs::copy(iso_tree.join("boot/grub/grub.cfg"), dest.join("grub.cfg"))?;
			vendor_copied = true;
		}
		if !vendor_copied {
			bail!(
				"No EFI vendor directory (fedora/centos/redhat) found under {}; \
				 grub's second stage would be missing",
				efi_root.display()
			);
		}

		// shim's DEFAULT_LOADER, which it resolves next to itself.
		let expected_second_stage = match arch_short_upper.as_str() {
			"X64" => "grubx64.efi",
			"AA64" => "grubaa64.efi",
			other => bail!("Unsupported EFI architecture {other}"),
		};
		if !Self::find_file_recursive(&iso_tree.join("EFI"), expected_second_stage)? {
			bail!(
				"No {expected_second_stage} in the EFI tree; shim has nothing to chainload, \
				 which the firmware will report as a failed boot"
			);
		}

		// Conventional for removable media; shim's package already provides one.
		let boot_alias = boot_out.join(format!("BOOT{arch_short_upper}.EFI"));
		if !boot_alias.exists() {
			let shim = efi_root.join(format!("fedora/shim{}.efi", self.get_arch_short(manifest)));
			if shim.is_file() {
				debug!(?shim, ?boot_alias, "Aliasing shim as the removable-media loader");
				fs::copy(&shim, &boot_alias)?;
			} else {
				bail!("No removable-media loader (BOOTX64.EFI) and no shim at {}", shim.display());
			}
		}

		// GRUB's own config and fonts, next to the second stage.
		fs::create_dir_all(boot_out.join("fonts"))?;
		cmd_lib::run_cmd!(
			cp -av $iso_tree/boot/grub/grub.cfg $boot_out/BOOT.conf 2>&1;
			cp -av $iso_tree/boot/grub/grub.cfg $boot_out/grub.cfg 2>&1;
			cp -av $iso_tree/boot/grub/fonts/unicode.pf2 $boot_out/fonts 2>&1;
		)?;

		Ok(())
	}

	/// Whether any file with this name exists anywhere under `dir`.
	fn find_file_recursive(dir: &Path, name: &str) -> Result<bool> {
		if !dir.is_dir() {
			return Ok(false);
		}
		for entry in fs::read_dir(dir)? {
			let entry = entry?;
			let path = entry.path();
			if path.is_dir() {
				if Self::find_file_recursive(&path, name)? {
					return Ok(true);
				}
			} else if path.file_name().is_some_and(|n| n == name) {
				return Ok(true);
			}
		}
		Ok(false)
	}

	fn get_arch<'a>(&self, manifest: &'a Manifest) -> &'a str {
		manifest.dnf.arch.as_deref().unwrap_or(std::env::consts::ARCH)
	}

	fn get_arch_short(&self, manifest: &Manifest) -> &'static str {
		match self.get_arch(manifest) {
			"x86_64" => "x64",
			"aarch64" => "aa64",
			_ => unimplemented!(),
		}
	}

	fn mkefiboot(&self, workspace: &Path, _: &Manifest) -> Result<()> {
		let tree = workspace.join(ISO_TREE);

		let sparse_path = &tree.join("boot/efiboot.img");
		crate::util::create_sparse(sparse_path, 25 * 1024 * 1024)?;

		let (ldp, hdl) = loopdev_with_file(sparse_path)?;

		// The whole EFI tree, since the CSV's chainload target lives in the vendor dir.
		cmd_lib::run_cmd!(
			mkfs.msdos $ldp -v -n EFI 2>&1;
			mkdir -p /tmp/katsu.efiboot;
			mount $ldp /tmp/katsu.efiboot;
			mkdir -p /tmp/katsu.efiboot/EFI;
			cp -avr $tree/EFI/. /tmp/katsu.efiboot/EFI/ 2>&1;
			umount /tmp/katsu.efiboot;
		)?;

		drop(hdl);
		Ok(())
	}

	fn generate_grub_images(
		&self, chroot: &Path, iso_tree: &Path, manifest: &Manifest,
	) -> Result<()> {
		let host_arch = std::env::consts::ARCH;
		let target_arch = manifest.dnf.arch.as_deref().unwrap_or(host_arch);

		let arch = match target_arch {
			"x86_64" => "i386-pc",
			"aarch64" => "arm64-efi",
			_ => unimplemented!(),
		};

		let arch_out = match target_arch {
			"x86_64" => "i386-pc-eltorito",
			"aarch64" => "arm64-efi",
			_ => unimplemented!(),
		};

		let arch_modules = match target_arch {
			"x86_64" => vec!["biosdisk"],
			"aarch64" => vec!["efi_gop"],
			_ => unimplemented!(),
		};

		debug!("Generating Grub images");
		{
			use std::process::Command;

			let grub_mkimage_status = Command::new("grub2-mkimage")
				.arg("-O")
				.arg(arch_out)
				.arg("-d")
				.arg(chroot.join(format!("usr/lib/grub/{}", arch)))
				.arg("-o")
				.arg(iso_tree.join("boot/eltorito.img"))
				.arg("-p")
				.arg("/boot/grub")
				.arg("iso9660")
				.args(&arch_modules)
				.status()?;

			if !grub_mkimage_status.success() {
				bail!("grub2-mkimage command failed with status: {:?}", grub_mkimage_status);
			}

			let grub_mkrescue_status = Command::new("grub2-mkrescue")
				.arg("-o")
				.arg(iso_tree.join("../efiboot.img"))
				.status()?;

			if !grub_mkrescue_status.success() {
				bail!("grub2-mkrescue command failed with status: {:?}", grub_mkrescue_status);
			}
		}

		debug!("Copying EFI files from Grub rescue image");
		let (loop_device, handle) = loopdev_with_file(&iso_tree.join("../efiboot.img"))?;

		cmd_lib::run_cmd!(
			mkdir -p /tmp/katsu-efiboot;
			mount $loop_device /tmp/katsu-efiboot;
			cp -r /tmp/katsu-efiboot/boot/grub $iso_tree/boot/;
			umount /tmp/katsu-efiboot;
		)?;

		drop(handle);

		Ok(())
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use std::fs;

	/// Reproduces the layout shipped by Fedora 44 bootc/ostree images built with
	/// bootupd's `usr/lib/efi` component layout: `ostree-boot/efi` is an empty
	/// shell while the real payload lives under `usr/lib/efi/<name>/<version>/EFI`.
	fn make_usr_lib_efi(root: &Path) {
		let write = |rel: &str| {
			let p = root.join(rel);
			fs::create_dir_all(p.parent().unwrap()).unwrap();
			fs::write(p, b"x").unwrap();
		};

		// shim ships both the fallback BOOT dir and the vendor dir.
		write("usr/lib/efi/shim/15.8-3/EFI/BOOT/BOOTX64.EFI");
		write("usr/lib/efi/shim/15.8-3/EFI/BOOT/fbx64.efi");
		write("usr/lib/efi/shim/15.8-3/EFI/fedora/shim.efi");
		write("usr/lib/efi/shim/15.8-3/EFI/fedora/shimx64.efi");
		// grub2 ships the vendor dir only, with a colon in the version.
		write("usr/lib/efi/grub2/1:2.12-43.fc43/EFI/fedora/grubx64.efi");
	}

	fn empty_ostree_boot_efi(root: &Path) {
		fs::create_dir_all(root.join("usr/lib/ostree-boot/efi/EFI")).unwrap();
	}

	#[test]
	fn collects_payload_from_usr_lib_efi_when_ostree_boot_is_empty() {
		let tmp = std::env::temp_dir().join("katsu-grub-efi-f44");
		let _ = fs::remove_dir_all(&tmp);
		make_usr_lib_efi(&tmp);
		empty_ostree_boot_efi(&tmp);

		let efi_dest = tmp.join("iso/boot/efi");
		let chroot_boot = tmp.join("usr/lib/ostree-boot");
		Bootloader::copy_efi_payload(&tmp, &chroot_boot, &efi_dest, true).unwrap();

		assert!(efi_dest.join("EFI/fedora/shimx64.efi").is_file());
		assert!(efi_dest.join("EFI/fedora/grubx64.efi").is_file());
		assert!(efi_dest.join("EFI/BOOT/BOOTX64.EFI").is_file());
	}

	#[test]
	fn prefers_populated_boot_efi_over_empty_usr_lib_efi() {
		let tmp = std::env::temp_dir().join("katsu-grub-efi-legacy");
		let _ = fs::remove_dir_all(&tmp);
		fs::create_dir_all(&tmp).unwrap();

		let vendor = tmp.join("usr/lib/ostree-boot/efi/EFI/fedora");
		fs::create_dir_all(&vendor).unwrap();
		fs::write(vendor.join("shimx64.efi"), b"x").unwrap();

		let efi_dest = tmp.join("iso/boot/efi");
		let chroot_boot = tmp.join("usr/lib/ostree-boot");
		Bootloader::copy_efi_payload(&tmp, &chroot_boot, &efi_dest, true).unwrap();

		assert!(efi_dest.join("EFI/fedora/shimx64.efi").is_file());
	}

	#[test]
	fn grub_staging_preserves_the_live_initramfs() {
		let tmp =
			std::env::temp_dir().join(format!("katsu-grub-live-initrd-{}", std::process::id()));
		let chroot = tmp.join("rootfs");
		let modules = chroot.join("usr/lib/modules/test-kernel");
		fs::create_dir_all(&modules).unwrap();
		fs::write(modules.join("vmlinuz"), b"kernel").unwrap();
		fs::write(modules.join("initramfs.img"), b"disk initramfs").unwrap();
		make_usr_lib_efi(&chroot);
		empty_ostree_boot_efi(&chroot);
		fs::create_dir_all(chroot.join("usr/lib/grub")).unwrap();
		fs::create_dir_all(chroot.join("usr/share/grub")).unwrap();
		fs::write(chroot.join("usr/share/grub/unicode.pf2"), b"font").unwrap();

		let iso_tree = tmp.join("iso-tree");
		fs::create_dir_all(iso_tree.join("boot")).unwrap();
		fs::write(iso_tree.join("boot/initramfs.img"), b"live initramfs").unwrap();
		Bootloader::Grub
			.copy_kernel_and_initramfs(&chroot, &tmp.join("boot_imgs"), &iso_tree)
			.unwrap();

		assert_eq!(fs::read(iso_tree.join("boot/initramfs.img")).unwrap(), b"live initramfs");
		assert_eq!(fs::read(iso_tree.join("boot/vmlinuz")).unwrap(), b"kernel");
		fs::remove_dir_all(tmp).unwrap();
	}

	#[test]
	fn installs_grub_config_at_the_vendor_prefix() {
		let tmp =
			std::env::temp_dir().join(format!("katsu-grub-vendor-config-{}", std::process::id()));
		fs::create_dir_all(&tmp).unwrap();
		make_usr_lib_efi(&tmp);
		let iso_tree = tmp.join("iso");
		Bootloader::copy_usr_lib_efi(&tmp.join("usr/lib/efi"), &iso_tree.join("boot/efi/EFI"))
			.unwrap();
		let vendor = iso_tree.join("boot/efi/EFI/fedora");
		let csv = b"shimx64.efi,Fedora,,This is the boot entry for Fedora\n";
		fs::write(vendor.join("BOOTX64.CSV"), csv).unwrap();
		fs::write(vendor.join("grub.cfg"), b"stale vendor config").unwrap();

		fs::create_dir_all(iso_tree.join("boot/grub/fonts")).unwrap();
		let config = b"search --label KATSU-LIVEOS\nmenuentry 'Live' {}\n";
		fs::write(iso_tree.join("boot/grub/grub.cfg"), config).unwrap();
		fs::write(iso_tree.join("boot/grub/fonts/unicode.pf2"), b"font").unwrap();
		let manifest: Manifest = serde_yaml::from_str("dnf:\n  arch: x86_64\n").unwrap();

		Bootloader::Grub.setup_efi_boot_files(&manifest, &iso_tree).unwrap();

		assert_eq!(fs::read(iso_tree.join("EFI/fedora/grub.cfg")).unwrap(), config);
		assert_eq!(fs::read(iso_tree.join("EFI/BOOT/grub.cfg")).unwrap(), config);
		assert_eq!(fs::read(iso_tree.join("EFI/fedora/BOOTX64.CSV")).unwrap(), csv);
		assert!(!iso_tree.join("EFI/BOOT/BOOTX64.CSV").exists());
		fs::remove_dir_all(tmp).unwrap();
	}

	#[test]
	fn errors_when_no_efi_payload_exists_on_ostree_boot_image() {
		let tmp = std::env::temp_dir().join("katsu-grub-efi-missing");
		let _ = fs::remove_dir_all(&tmp);
		empty_ostree_boot_efi(&tmp);

		let efi_dest = tmp.join("iso/boot/efi");
		let chroot_boot = tmp.join("usr/lib/ostree-boot");
		let res = Bootloader::copy_efi_payload(&tmp, &chroot_boot, &efi_dest, true);

		assert!(res.is_err(), "expected a hard error instead of an empty EFI tree");
	}
}
