use color_eyre::{Result, eyre::bail};
use serde::{Deserialize, Serialize};
use std::{
	fs,
	path::{Path, PathBuf},
};
use tracing::{debug, info, trace, warn};

use crate::config::Manifest;

mod grub;
mod limine;
mod refind;

/// Information about an OSTree deployment that the bootloader must be aware of.
///
/// When the root builder produced an OSTree sysroot rather than a plain rootfs,
/// the system is booted by having the initramfs locate the deployment via the
/// `ostree=` kernel argument, instead of `root=live:` alone. We carry that
/// knowledge here so the bootloader backends can emit the right config without
/// each of them re-deriving the ostree layout.
#[derive(Debug, Clone)]
pub struct OstreeDeployment {
	/// The `ostree=` kernel argument, e.g.
	/// `ostree=/ostree/boot.1/um/<bootcsum>/0`.
	pub karg: String,
}

/// Kernel arguments and payload paths needed to boot the produced tree.
///
/// An OSTree sysroot and a composefs root both boot through their own kernel
/// argument instead of `root=live:` alone, but they carry different values and
/// different kernel/initramfs locations. Collapsing them here keeps each
/// bootloader backend from having to know which layout it is looking at.
#[derive(Debug, Clone, Default)]
pub struct BootPayload {
	/// The deployment-selecting kernel argument (`ostree=` or `composefs=`),
	/// empty for a plain rootfs.
	pub karg: String,
	/// Kernel path below the tree root, when the layout dictates it.
	pub vmlinuz: Option<PathBuf>,
	/// Initramfs path below the tree root, when the layout dictates it.
	pub initramfs: Option<PathBuf>,
}

impl BootPayload {
	/// Resolve whichever deployment layout the tree uses, if any.
	pub fn resolve(tree: &Path) -> Result<Self> {
		if let Some(ostree) = OstreeDeployment::resolve(tree)? {
			return Ok(Self { karg: ostree.karg, vmlinuz: None, initramfs: None });
		}
		if let Some(composefs) = ComposefsDeployment::resolve(tree)? {
			return Ok(Self {
				karg: composefs.karg,
				vmlinuz: Some(composefs.vmlinuz),
				initramfs: Some(composefs.initramfs),
			});
		}
		Ok(Self::default())
	}
}

/// Information a bootloader needs for a native composefs deployment.
///
/// A composefs root is not selected by `ostree=`. Its BLS entry instead passes
/// `composefs=<verity digest>`, where the digest is a 128-character SHA-512
/// fs-verity identifier that we must not reconstruct ourselves. The kernel and
/// initramfs also live under `boot/bootc_composefs-<D>/` rather than `/boot`.
#[derive(Debug, Clone)]
pub struct ComposefsDeployment {
	/// The `composefs=` kernel argument, e.g. `composefs=<verity digest>`.
	pub karg: String,
	/// Path of the kernel below the tree root.
	pub vmlinuz: PathBuf,
	/// Path of the initramfs below the tree root.
	pub initramfs: PathBuf,
}

impl ComposefsDeployment {
	/// Resolve the composefs deployment from the BLS entry generated by bootc.
	///
	/// The BLS entry is authoritative: it carries the verity digest and the
	/// kernel/initrd locations bootc chose. Reconstructing those from the
	/// directory layout would be guessing, since the digest is an fs-verity
	/// identifier rather than the OCI digest or an ostree checksum.
	pub fn resolve(tree: &Path) -> Result<Option<Self>> {
		let entries_dir = tree.join("boot/loader/entries");
		let Ok(entries) = fs::read_dir(&entries_dir) else {
			return Ok(None);
		};

		// Only one deployment is ever installed, so the single BLS entry is ours.
		for entry in entries.flatten() {
			let path = entry.path();
			if path.extension().is_some_and(|e| e != "conf") {
				continue;
			}
			let Ok(contents) = fs::read_to_string(&path) else {
				continue;
			};

			let mut karg = None;
			let mut vmlinuz = None;
			let mut initramfs = None;
			for line in contents.lines() {
				let line = line.trim();
				if let Some(options) = line.strip_prefix("options ") {
					karg = options
						.split_whitespace()
						.find(|o| o.starts_with("composefs="))
						.map(|o| o.to_string());
				} else if let Some(linux) = line.strip_prefix("linux ") {
					vmlinuz = Some(linux.trim().trim_start_matches('/').to_string());
				} else if let Some(initrd) = line.strip_prefix("initrd ") {
					initramfs = Some(initrd.trim().trim_start_matches('/').to_string());
				}
			}

			let (Some(karg), Some(vmlinuz), Some(initramfs)) = (karg, vmlinuz, initramfs) else {
				debug!(?path, "BLS entry is not a composefs deployment; ignoring");
				continue;
			};

			let vmlinuz = tree.join(&vmlinuz);
			let initramfs = tree.join(&initramfs);
			if !vmlinuz.is_file() || !initramfs.is_file() {
				bail!(
					"Composefs BLS entry references missing files: {} / {}",
					vmlinuz.display(),
					initramfs.display()
				);
			}

			debug!(?path, %karg, "Resolved composefs deployment");
			return Ok(Some(Self { karg, vmlinuz, initramfs }));
		}

		Ok(None)
	}
}

impl OstreeDeployment {
	/// Resolve the OSTree deployment for a tree root, if it is a sysroot.
	///
	/// `tree` is either the deployment root (`ostree/deploy/<stateroot>/deploy/
	/// <csum>.0`) or an ostree sysroot. We detect the deployment root by walking
	/// up to the sysroot, then locate the matching boot-linkage directory under
	/// `ostree/boot.<n>/`.
	pub fn resolve(tree: &Path) -> Result<Option<Self>> {
		let Some((sysroot, stateroot, csum)) = Self::locate(tree) else {
			return Ok(None);
		};

		let Some(karg) = Self::find_karg(&sysroot, &stateroot, &csum)? else {
			warn!(
				?sysroot,
				"Found an OSTree deployment but no boot linkage; \
				 the system will not be able to locate it at boot"
			);
			return Ok(None);
		};

		debug!(?sysroot, %karg, "Resolved OSTree deployment");
		Ok(Some(Self { karg }))
	}

	/// Walk from either a sysroot or a deployment root to `(sysroot, stateroot, csum)`.
	fn locate(tree: &Path) -> Option<(PathBuf, String, String)> {
		// Case 1: `tree` is the deployment root itself.
		// <sysroot>/ostree/deploy/<stateroot>/deploy/<csum>.0
		if let Some(deploy_dir) = tree.parent()
			&& deploy_dir.file_name().is_some_and(|n| n == "deploy")
			&& let Some(stateroot_dir) = deploy_dir.parent()
			&& let Some(stateroot) =
				stateroot_dir.file_name().map(|n| n.to_string_lossy().to_string())
			&& let Some(deploy_base) = stateroot_dir.parent()
			// `sysroot/ostree/deploy` -> `sysroot/ostree` -> `sysroot`
			&& let Some(sysroot) = deploy_base.parent().and_then(|p| p.parent())
		{
			let csum = tree.file_name()?.to_string_lossy().to_string();
			return Some((sysroot.to_path_buf(), stateroot, csum));
		}

		// Case 2: `tree` is a sysroot; find the single deployed commit.
		let deploy_base = tree.join("ostree/deploy");
		for stateroot_entry in fs::read_dir(&deploy_base).ok()?.flatten() {
			let stateroot = stateroot_entry.file_name().to_string_lossy().to_string();
			let deploy_dir = stateroot_entry.path().join("deploy");
			if let Ok(deployment) = crate::backends::fs_tree::find_deployment(&deploy_dir) {
				let csum = deployment.file_name()?.to_string_lossy().to_string();
				return Some((tree.to_path_buf(), stateroot, csum));
			}
		}

		None
	}

	/// Find the `ostree=` kernel argument for a deployment.
	///
	/// ostree writes the authoritative value into the BLS entry it generates under
	/// `<sysroot>/boot/loader.<n>/entries/`. We read it from there rather than
	/// reconstructing it: the path contains a boot checksum and a boot-version
	/// directory (`boot.1`, `boot.1.1`, ...) that are ostree's to decide, and the
	/// `.origin` file does not record them at all.
	///
	/// Deployments are identified by their kernel/initrd paths, which are prefixed
	/// with `<stateroot>-<boot-checksum>`. Note this is the *boot* checksum, not
	/// the deployment directory's commit checksum, so we cannot match on the
	/// latter directly; instead we group entries by stateroot.
	fn find_karg(sysroot: &Path, stateroot: &str, csum: &str) -> Result<Option<String>> {
		let Some(entries_dir) = Self::find_loader_entries_dir(&sysroot.join("boot"))? else {
			debug!(?sysroot, "No boot loader entries directory found");
			return Ok(None);
		};

		// The deployment's own directory name is `<commit csum>.0`; the number after
		// the dot is the boot version, which `ostree=` also carries as its last
		// component.
		let boot_version = csum.rsplit_once('.').map(|(_, v)| v).unwrap_or("0");
		let prefix = format!("{stateroot}-");

		for entry in fs::read_dir(&entries_dir)?.flatten() {
			let path = entry.path();
			if path.extension().is_none_or(|ext| ext != "conf") {
				continue;
			}
			let Ok(contents) = fs::read_to_string(&path) else {
				continue;
			};

			// Match the entry to this stateroot via the kernel/initrd path prefix.
			let belongs = contents
				.lines()
				.filter(|l| l.starts_with("linux ") || l.starts_with("initrd "))
				.any(|l| l.contains(&format!("/ostree/{prefix}")));
			if !belongs {
				continue;
			}

			// If several deployments share a stateroot the boot version disambiguates.
			let karg = contents
				.lines()
				.find_map(|line| line.strip_prefix("options "))
				.and_then(|opts| opts.split_whitespace().find(|w| w.starts_with("ostree=")))
				.map(|s| s.to_string());

			let Some(karg) = karg else {
				warn!(?path, "BLS entry has no ostree= option");
				continue;
			};

			if karg.ends_with(&format!("/{boot_version}")) {
				debug!(?path, %karg, "Read ostree karg from BLS entry");
				return Ok(Some(karg));
			}
		}

		Ok(None)
	}

	/// Locate the `loader.<n>/entries` directory ostree wrote boot entries into.
	///
	/// ostree versions this directory (`loader.1`, `loader.2`, ...), and also
	/// maintains a `loader` symlink to the active one, so prefer the symlink when
	/// it resolves.
	fn find_loader_entries_dir(boot_dir: &Path) -> Result<Option<PathBuf>> {
		let linked = boot_dir.join("loader/entries");
		if linked.is_dir() {
			return Ok(Some(linked));
		}

		// A deployment may exist with no boot directory at all (for example a tree
		// that was never scanned by ostree), which is not an error here.
		let Ok(entries) = fs::read_dir(boot_dir) else {
			return Ok(None);
		};

		for entry in entries.flatten() {
			let name = entry.file_name();
			let name = name.to_string_lossy();
			if name.starts_with("loader.") {
				let entries = entry.path().join("entries");
				if entries.is_dir() {
					return Ok(Some(entries));
				}
			}
		}

		Ok(None)
	}
}

crate::prepend_comment!(GRUB_PREPEND_COMMENT: "/boot/grub/grub.cfg", "Grub configurations", katsu::builder::Bootloader::cp_grub);
crate::prepend_comment!(LIMINE_PREPEND_COMMENT: "/boot/limine.cfg", "Limine configurations", katsu::builder::Bootloader::cp_limine);
crate::prepend_comment!(REFIND_PREPEND_COMMENT: "/boot/efi/EFI/refind/refind.conf", "rEFInd configurations", katsu::builder::Bootloader::cp_refind);

/// Represents the bootloader types supported by Katsu
///
/// This enum defines the different bootloader implementations that can be used
/// when creating bootable images. Each variant corresponds to a specific
/// bootloader technology with its own installation and configuration methods.
#[derive(Default, Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Bootloader {
	#[default]
	/// Standard GRUB2 bootloader with UEFI support (default)
	Grub,
	/// GRUB2 bootloader configured for legacy BIOS systems
	GrubBios,
	/// Limine bootloader, a modern UEFI/BIOS bootloader
	Limine,
	/// systemd-boot, a simple UEFI boot manager
	SystemdBoot,
	/// rEFInd, a graphical UEFI boot manager
	REFInd,
}

impl From<&str> for Bootloader {
	fn from(value: &str) -> Self {
		match &*value.to_lowercase() {
			"limine" => Self::Limine,
			"grub" | "grub2" => Self::Grub,
			"grub-bios" => Self::GrubBios,
			"systemd-boot" => Self::SystemdBoot,
			"refind" => Self::REFInd,
			_ => {
				warn!("Unknown bootloader: {value}, falling back to GRUB");
				Self::Grub
			},
		}
	}
}

impl Bootloader {
	/// Installs the bootloader to the specified image
	///
	/// This method is responsible for actually installing the bootloader to the
	/// target image after it has been created. Different bootloaders require
	/// different installation procedures.
	///
	/// # Arguments
	///
	/// * `image` - The path to the image file where the bootloader will be installed
	///
	/// # Returns
	///
	/// * `Result<()>` - Success or failure with error details
	pub fn install(&self, image: &Path) -> Result<()> {
		match *self {
			Self::Grub => info!("GRUB is not required to be installed to image, skipping"),
			Self::Limine => cmd_lib::run_cmd!(limine bios-install $image 2>&1)?,
			Self::SystemdBoot => cmd_lib::run_cmd!(bootctl --image=$image install 2>&1)?,
			Self::GrubBios => {
				cmd_lib::run_cmd!(grub-install --target=i386-pc --boot-directory=$image/boot 2>&1)?
			},
			Self::REFInd => info!(
				"rEFInd doesn't need installation to ISO image, files already copied during ISO creation"
			),
		}
		Ok(())
	}
	/// Returns the paths to the UEFI and BIOS bootloader binaries
	///
	/// This method provides the relative paths to the bootloader binaries needed
	/// for creating bootable media. These paths are used during the ISO creation
	/// process to locate the appropriate files for UEFI and BIOS boot support.
	///
	/// # Returns
	///
	/// * A tuple of `(&'static str, &'static str)` containing:
	///   * First element: Path to the UEFI bootloader binary
	///   * Second element: Path to the BIOS bootloader binary
	pub fn get_bins(&self) -> (&'static str, &'static str) {
		match *self {
			Self::Grub => ("boot/efi/EFI/fedora/shim.efi", "boot/eltorito.img"),
			Self::Limine => ("boot/limine-uefi-cd.bin", "boot/limine-bios-cd.bin"),
			Self::GrubBios => todo!(),
			Self::SystemdBoot => todo!(),
			Self::REFInd => ("boot/efi/EFI/refind/refind_x64.efi", ""),
		}
	}
	/// Copies vmlinuz (and optionally initramfs) from /usr/lib/modules to destination
	///
	/// This helper method locates the kernel (vmlinuz) file in /usr/lib/modules
	/// and copies it to the destination directory. When requested, it will also
	/// copy the initramfs image from the chroot's `/boot` into the destination,
	/// normalising the name to `initramfs.img` so the rest of the ISO generation
	/// pipeline can rely on a consistent filename.
	///
	/// # Arguments
	///
	/// * `chroot` - The path to the chroot directory containing the kernel
	/// * `dest` - The destination directory where vmlinuz should be copied
	///
	/// # Returns
	///
	/// * `Result<String>` - Success with kernel filename or failure with error details
	fn cp_vmlinuz_initramfs(
		&self, chroot: &Path, dest: &Path, copy_initramfs: bool,
	) -> Result<(String, String)> {
		trace!("Finding vmlinuz in /usr/lib/modules");

		// Prepare required directories
		fs::create_dir_all(dest.join("boot"))?;

		// Find kernel version and vmlinuz
		let (vmlinuz, kernel_version) = self.find_vmlinuz(chroot)?;
		debug!(?vmlinuz, ?kernel_version, "Kernel version and vmlinuz found");

		// Copy vmlinuz to destination
		let vmlinuz_dest = dest.join("boot").join("vmlinuz");
		trace!(?vmlinuz, ?vmlinuz_dest, "Copying vmlinuz to destination");

		let vmlinuz_src = if vmlinuz.is_empty() {
			bail!("Could not find vmlinuz path");
		} else {
			PathBuf::from(&vmlinuz)
		};

		if !vmlinuz_src.exists() {
			bail!("Source vmlinuz not found at {}", vmlinuz_src.display());
		}

		fs::copy(&vmlinuz_src, &vmlinuz_dest)?;

		if copy_initramfs {
			let initramfs_dest = dest.join("boot").join("initramfs.img");

			// The `dracut` phase writes a live-capable initramfs directly into the
			// ISO tree. The image's own initramfs is built for a disk install and
			// cannot mount `root=live:`, so never let it clobber the generated one.
			if initramfs_dest.exists() {
				info!(
					?initramfs_dest,
					"Initramfs already present (from the dracut phase), not overwriting"
				);
			} else {
				let initramfs_src = self.find_initramfs(chroot)?;
				trace!(?initramfs_src, ?initramfs_dest, "Copying initramfs to destination");

				if !initramfs_src.exists() {
					bail!("Source initramfs not found at {}", initramfs_src.display());
				}

				fs::copy(&initramfs_src, &initramfs_dest)?;
			}
		}

		Ok(("vmlinuz".to_string(), "initramfs.img".to_string()))
	}

	#[tracing::instrument(skip(self))]
	fn find_vmlinuz(&self, chroot: &Path) -> Result<(String, Option<String>)> {
		let modules_dir = chroot.join("usr/lib/modules");

		// Find kernel version from modules directory
		let mut kernels = fs::read_dir(&modules_dir)?;
		let kernel_version = kernels.find_map(|f| {
			trace!(?f, "File in /usr/lib/modules");
			f.ok().and_then(|entry| entry.file_name().to_str().map(|s| s.to_string()))
		});

		trace!("Kernel version found: {:?}", kernel_version);

		// Determine vmlinuz path based on kernel version
		let vmlinuz = if let Some(ref kernel_version) = kernel_version {
			modules_dir.join(kernel_version).join("vmlinuz").to_string_lossy().to_string()
		} else {
			// If no kernel version found, we'll try to find vmlinuz in boot directory later
			String::new()
		};

		Ok((vmlinuz, kernel_version))
	}

	#[tracing::instrument(skip(self))]
	#[allow(dead_code)]
	fn find_initramfs(&self, chroot: &Path) -> Result<PathBuf> {
		// Newer bootc/ostree images keep `/boot` empty and place the initramfs
		// next to the kernel under /usr/lib/modules/<kver>/, or in the
		// kernel-install layout under /usr/lib/ostree-boot/<stateroot>/<kver>/.
		// Only fall back to a populated /boot for older images.
		if let Some(path) = Self::find_initramfs_in_usr_lib_modules(chroot)? {
			return Ok(path);
		}

		let bootdir = chroot.join("boot");

		// Search for initramfs in boot directory
		for f in bootdir.read_dir()? {
			let f = f?;
			if !f.metadata()?.is_file() {
				continue;
			}

			let name = f.file_name();
			debug!(?name, "File in /boot");
			let name = name.to_string_lossy();

			// Skip rescue images
			if name.contains("-rescue-") {
				continue;
			}

			// Look for initramfs files
			if name == "initramfs.img" || name.starts_with("initramfs-") {
				return Ok(f.path());
			}
		}

		bail!("Cannot find initramfs in {:?}", bootdir)
	}

	/// Look for an initramfs under /usr/lib/modules/<kver>/.
	fn find_initramfs_in_usr_lib_modules(chroot: &Path) -> Result<Option<PathBuf>> {
		let modules_dir = chroot.join("usr/lib/modules");
		let Ok(entries) = fs::read_dir(&modules_dir) else {
			return Ok(None);
		};

		for entry in entries.flatten() {
			let dir = entry.path();
			if !dir.is_dir() {
				continue;
			}
			for candidate in ["initramfs.img", "initramfs"] {
				let path = dir.join(candidate);
				if path.is_file() {
					debug!(?path, "Found initramfs under /usr/lib/modules");
					return Ok(Some(path));
				}
			}

			// Any `initramfs*`/`initrd*` file in the module dir will do.
			if let Ok(files) = fs::read_dir(&dir) {
				for file in files.flatten() {
					let name = file.file_name().to_string_lossy().to_string();
					if file.path().is_file()
						&& (name.starts_with("initramfs") || name.starts_with("initrd"))
						&& !name.contains("-rescue-")
					{
						let path = file.path();
						debug!(?path, "Found initramfs under /usr/lib/modules");
						return Ok(Some(path));
					}
				}
			}
		}

		Ok(None)
	}

	#[tracing::instrument(skip(self))]
	#[allow(dead_code)]
	fn copy_boot_files(
		&self, chroot: &Path, dest: &Path, vmlinuz: &str, initramfs: &str,
	) -> Result<()> {
		let bootdir = chroot.join("boot");

		trace!(vmlinuz, initramfs, "Copying vmlinuz and initramfs");

		// Copy vmlinuz to destination
		let vmlinuz_dest = dest.join("boot").join("vmlinuz");
		trace!(?vmlinuz, ?vmlinuz_dest, "Copying vmlinuz to destination");
		let vmlinuz_src =
			if vmlinuz.is_empty() { bootdir.join("vmlinuz") } else { PathBuf::from(vmlinuz) };
		if !vmlinuz_src.exists() {
			bail!("Source vmlinuz not found at {}", vmlinuz_src.display());
		}
		fs::copy(&vmlinuz_src, &vmlinuz_dest)?;

		// Copy initramfs to destination
		let initramfs_src = bootdir.join(initramfs);
		let initramfs_dest = dest.join("boot").join("initramfs.img");
		if !initramfs_src.exists() {
			bail!("Source initramfs not found at {}", initramfs_src.display());
		}
		fs::copy(&initramfs_src, &initramfs_dest)?;

		// === start /boot cleanup ===
		if let Err(err) = fs::remove_file(&vmlinuz_src) {
			warn!(?err, path = %vmlinuz_src.display(), "Failed to remove source vmlinuz after copying");
		}
		if let Err(err) = fs::remove_file(&initramfs_src) {
			warn!(?err, path = %initramfs_src.display(), "Failed to remove source initramfs after copying");
		}

		// remove the rescue initramfs and vmlinuz if they exist
		let rescue_initramfs = bootdir.read_dir()?.find_map(|f| {
			let f = f.ok()?;
			let name = f.file_name().to_string_lossy().to_string();
			if name.contains("-rescue-") { Some(f.path()) } else { None }
		});

		if let Some(rescue_initramfs) = rescue_initramfs
			&& let Err(err) = fs::remove_file(&rescue_initramfs)
		{
			warn!(?err, path = %rescue_initramfs.display(), "Failed to remove rescue initramfs after copying");
		}

		let rescue_vmlinuz = bootdir.read_dir()?.find_map(|f| {
			let f = f.ok()?;
			let name = f.file_name().to_string_lossy().to_string();
			if name.contains("-rescue-") { Some(f.path()) } else { None }
		});

		if let Some(rescue_vmlinuz) = rescue_vmlinuz
			&& let Err(err) = fs::remove_file(&rescue_vmlinuz)
		{
			warn!(?err, path = %rescue_vmlinuz.display(), "Failed to remove rescue vmlinuz after copying");
		}

		// === end /boot cleanup ===

		Ok(())
	}

	/// Copies the bootloader files to the live OS image
	///
	/// This method copies all necessary bootloader files to the ISO tree to create
	/// a bootable live OS image. The specific files copied depend on the bootloader type.
	/// This is one of the main methods used during the ISO creation process.
	///
	/// # Arguments
	///
	/// * `manifest` - The manifest containing configuration information
	/// * `chroot` - The path to the chroot directory
	/// * `workspace` - The path to the workspace directory
	///
	/// # Returns
	///
	/// * `Result<()>` - Success or failure with error details
	pub fn copy_liveos(&self, manifest: &Manifest, chroot: &Path, workspace: &Path) -> Result<()> {
		info!("Copying bootloader files");
		// For an OSTree sysroot the deployment is not at the tree root, so resolve
		// the boot payload location and the deployment-selecting kernel argument.
		let payload = BootPayload::resolve(chroot)?;
		if !payload.karg.is_empty() {
			info!(karg = %payload.karg, "Resolved deployment boot argument");
		}
		match *self {
			Self::Grub => self.cp_grub(manifest, chroot, workspace, &payload)?,
			Self::Limine => self.cp_limine(manifest, chroot, workspace, &payload)?,
			Self::SystemdBoot => todo!(),
			Self::GrubBios => self.cp_grub_bios(workspace)?,
			Self::REFInd => self.cp_refind(manifest, chroot, workspace, &payload)?,
		}
		Ok(())
	}

	/// Copies GRUB BIOS-specific files to the ISO tree
	///
	/// This method is responsible for setting up the legacy BIOS boot environment
	/// using GRUB. It's used when the bootloader type is GrubBios.
	///
	/// # Arguments
	///
	/// * `_workspace` - The path to the workspace directory
	///
	/// # Returns
	///
	/// * `Result<()>` - Success or failure with error details
	pub fn cp_grub_bios(&self, _workspace: &Path) -> Result<()> {
		todo!()
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use std::fs;

	const CSUM: &str = "0123456789abcdef";
	const BOOTCSUM: &str = "deadbeefcafe";
	const VERITY: &str = "c88912e35a047d05e878f3b690f9a411a15757e5f8b1931df5d3954a56a8c6dea0871ac4cf283eb5260a547c7e1ea2c797c734455aa79341bd01c14d57bd07e3";

	/// Build a minimal tree shaped like a native composefs install.
	fn make_composefs_tree(name: &str) -> PathBuf {
		let tree = std::env::temp_dir().join(name);
		let _ = fs::remove_dir_all(&tree);

		let boot = tree.join(format!("boot/bootc_composefs-{VERITY}"));
		fs::create_dir_all(&boot).unwrap();
		fs::write(boot.join("vmlinuz"), b"kernel").unwrap();
		fs::write(boot.join("initrd"), b"initrd").unwrap();

		let entries = tree.join("boot/loader/entries");
		fs::create_dir_all(&entries).unwrap();
		fs::write(
			entries.join("bootc_ultramarine-44-1.conf"),
			format!(
				"title Ultramarine Linux 44\n\
				 version 44\n\
				 linux /boot/bootc_composefs-{VERITY}/vmlinuz\n\
				 initrd /boot/bootc_composefs-{VERITY}/initrd\n\
				 options root=UUID=abc rw composefs={VERITY} quiet rhgb\n"
			),
		)
		.unwrap();
		tree
	}

	#[test]
	fn resolves_a_composefs_deployment_from_its_bls_entry() {
		let tree = make_composefs_tree("katsu-composefs-resolve");

		let deployment =
			ComposefsDeployment::resolve(&tree).unwrap().expect("should resolve composefs");

		assert_eq!(deployment.karg, format!("composefs={VERITY}"));
		// The kernel and initramfs are not under /boot, so their resolved paths
		// must be carried for the bootloader to copy them.
		assert_eq!(deployment.vmlinuz, tree.join(format!("boot/bootc_composefs-{VERITY}/vmlinuz")));
		assert_eq!(
			deployment.initramfs,
			tree.join(format!("boot/bootc_composefs-{VERITY}/initrd"))
		);
	}

	#[test]
	fn boot_payload_prefers_composefs_over_a_plain_rootfs() {
		let tree = make_composefs_tree("katsu-bootpayload-composefs");
		let payload = BootPayload::resolve(&tree).unwrap();
		assert!(payload.karg.starts_with("composefs="));
		assert!(payload.vmlinuz.is_some());
	}

	#[test]
	fn boot_payload_is_empty_for_a_plain_rootfs() {
		let root = std::env::temp_dir().join("katsu-bootpayload-plain");
		let _ = fs::remove_dir_all(&root);
		fs::create_dir_all(root.join("usr/bin")).unwrap();

		let payload = BootPayload::resolve(&root).unwrap();
		assert!(payload.karg.is_empty());
		assert!(payload.vmlinuz.is_none());
	}

	#[test]
	fn errors_when_a_bls_entry_references_missing_files() {
		let tree = make_composefs_tree("katsu-composefs-missing");
		fs::remove_file(tree.join(format!("boot/bootc_composefs-{VERITY}/vmlinuz"))).unwrap();

		// A BLS entry pointing at absent files must fail loudly rather than
		// silently producing an unbootable ISO.
		assert!(ComposefsDeployment::resolve(&tree).is_err());
	}

	/// Build a minimal sysroot shaped like the one `ostree admin deploy` produces.
	fn make_sysroot(name: &str) -> PathBuf {
		let sysroot = std::env::temp_dir().join(name);
		let _ = fs::remove_dir_all(&sysroot);

		let deploy = sysroot.join("ostree/deploy/um/deploy");
		fs::create_dir_all(deploy.join(format!("{CSUM}.0"))).unwrap();
		fs::write(deploy.join(format!("{CSUM}.0.origin")), b"[origin]\nrefspec=um/44/x86_64\n")
			.unwrap();

		// ostree versions the boot directory and keeps a `loader` symlink; our
		// resolver should find entries either way.
		fs::create_dir_all(sysroot.join("ostree").join(format!("boot.1.1/um/{BOOTCSUM}"))).unwrap();

		let entries = sysroot.join("boot/loader.1/entries");
		fs::create_dir_all(&entries).unwrap();
		fs::write(
			entries.join("ostree-1.conf"),
			format!(
				"title Ultramarine Linux 44\n\
				 version 1\n\
				 options ostree=/ostree/boot.1/um/{BOOTCSUM}/0 quiet\n\
				 linux /ostree/um-{BOOTCSUM}/vmlinuz\n\
				 initrd /ostree/um-{BOOTCSUM}/initramfs.img\n"
			),
		)
		.unwrap();

		sysroot
	}

	#[test]
	fn resolve_builds_karg_from_a_sysroot() {
		let sysroot = make_sysroot("katsu-ostree-karg-sysroot");

		let deployment = OstreeDeployment::resolve(&sysroot).unwrap().expect("should resolve");

		assert_eq!(deployment.karg, format!("ostree=/ostree/boot.1/um/{BOOTCSUM}/0"));
	}

	/// The bootloader is handed the deployment root, not the sysroot, so the
	/// resolver has to walk back up to find the repo and boot linkage.
	#[test]
	fn resolve_works_from_the_deployment_root() {
		let sysroot = make_sysroot("katsu-ostree-karg-deploy");
		let deployment_root = sysroot.join(format!("ostree/deploy/um/deploy/{CSUM}.0"));

		let deployment =
			OstreeDeployment::resolve(&deployment_root).unwrap().expect("should resolve");

		assert_eq!(deployment.karg, format!("ostree=/ostree/boot.1/um/{BOOTCSUM}/0"));
	}

	/// Entries belonging to a different stateroot must not be picked up.
	#[test]
	fn resolve_ignores_entries_for_other_deployments() {
		let sysroot = make_sysroot("katsu-ostree-karg-other");
		let entries = sysroot.join("boot/loader.1/entries");
		// A second deployment under a different stateroot, written first so it is
		// encountered first.
		fs::write(
			entries.join("ostree-2.conf"),
			"options ostree=/ostree/boot.1/gnome/othercommit/0\n\
			 linux /ostree/gnome-othercommit/vmlinuz\n",
		)
		.unwrap();

		let deployment = OstreeDeployment::resolve(&sysroot).unwrap().expect("should resolve");

		assert_eq!(deployment.karg, format!("ostree=/ostree/boot.1/um/{BOOTCSUM}/0"));
	}

	/// Simulates the real call path end to end: `TreeOutput::rootfs()` returns the
	/// deployment root, which is then handed to `copy_liveos` and resolved.
	///
	/// The deployment directory sits under a populated `deploy/` containing a
	/// non-deployment sibling, mirroring what a build actually leaves behind.
	#[test]
	fn resolve_works_on_the_rootfs_returned_by_tree_output() {
		let sysroot = make_sysroot("katsu-ostree-karg-rootfs-path");
		// A stray directory in the same parent, as a stale build would leave.
		fs::create_dir_all(sysroot.join("ostree/deploy/um/deploy/iso-tree")).unwrap();

		let output = crate::backends::fs_tree::TreeOutput::OstreeSysroot {
			sysroot: sysroot.clone(),
			stateroot: "um".to_string(),
		};
		let rootfs = output.rootfs().unwrap();

		let deployment = OstreeDeployment::resolve(&rootfs).unwrap().expect("should resolve");

		assert_eq!(deployment.karg, format!("ostree=/ostree/boot.1/um/{BOOTCSUM}/0"));
	}

	/// A plain rootfs must not be mistaken for an OSTree deployment.
	#[test]
	fn resolve_returns_none_for_a_plain_rootfs() {
		let root = std::env::temp_dir().join("katsu-ostree-karg-plain");
		let _ = fs::remove_dir_all(&root);
		fs::create_dir_all(root.join("usr/bin")).unwrap();

		assert!(OstreeDeployment::resolve(&root).unwrap().is_none());
	}

	/// Without a BLS entry the deployment cannot be booted, so we must not emit a
	/// karg that would silently point at a nonexistent path.
	#[test]
	fn resolve_returns_none_when_no_bls_entry_exists() {
		let sysroot = std::env::temp_dir().join("katsu-ostree-karg-nobls");
		let _ = fs::remove_dir_all(&sysroot);
		let deploy = sysroot.join("ostree/deploy/um/deploy");
		fs::create_dir_all(deploy.join(format!("{CSUM}.0"))).unwrap();
		fs::write(deploy.join(format!("{CSUM}.0.origin")), b"[origin]\n").unwrap();

		// `resolve` walks from the deployment root; with no boot entries there is
		// nothing to read a karg from.
		let deployment = OstreeDeployment::resolve(&deploy.join(format!("{CSUM}.0"))).unwrap();

		assert!(deployment.is_none());
	}

	/// Fedora 44 bootc images leave /boot empty and put the initramfs next to
	/// the kernel under /usr/lib/modules/<kver>/. Older images used /boot.
	#[test]
	fn finds_initramfs_under_usr_lib_modules() {
		let root = std::env::temp_dir().join("katsu-initramfs-modules");
		let _ = fs::remove_dir_all(&root);
		fs::create_dir_all(root.join("boot")).unwrap();
		let modules = root.join("usr/lib/modules/7.1.12-200.fc44.x86_64");
		fs::create_dir_all(&modules).unwrap();
		fs::write(modules.join("initramfs.img"), b"x").unwrap();

		let found = Bootloader::find_initramfs_in_usr_lib_modules(&root).unwrap();

		assert_eq!(found, Some(modules.join("initramfs.img")));
	}

	/// Our test images still use the flat /boot layout, so that must keep working.
	#[test]
	fn finds_initramfs_in_boot() {
		let root = std::env::temp_dir().join("katsu-initramfs-boot");
		let _ = fs::remove_dir_all(&root);
		fs::create_dir_all(root.join("boot")).unwrap();
		fs::write(root.join("boot/initramfs-6.1.img"), b"x").unwrap();

		let found = Bootloader::default().find_initramfs(&root).unwrap();

		assert_eq!(found, root.join("boot/initramfs-6.1.img"));
	}

	/// Rescue initramfs images are not bootable targets for a live ISO.
	#[test]
	fn skips_rescue_initramfs_in_boot() {
		let root = std::env::temp_dir().join("katsu-initramfs-rescue");
		let _ = fs::remove_dir_all(&root);
		fs::create_dir_all(root.join("boot")).unwrap();
		fs::write(root.join("boot/initramfs-0-rescue-abc.img"), b"x").unwrap();
		fs::write(root.join("boot/initramfs-6.1.img"), b"x").unwrap();

		let found = Bootloader::default().find_initramfs(&root).unwrap();

		assert_eq!(found, root.join("boot/initramfs-6.1.img"));
	}
}
