name: ARM cross-build test

on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f38
      # Pass /dev from host to container
      # Very hacky, but it works
      # Microsoft/Github, if you're reading this,
      # I'm sorry.
      options: --privileged -v /dev:/dev

    steps:
      - uses: actions/checkout@v4
      - name: Cache DNF packages
        uses: actions/cache@v2
        with:
          path: /var/cache/dnf
          key: dnf-${{ runner.os }}
          restore-keys: |
            dnf-${{ runner.os }}-
            dnf-

      - name: Install dependencies
        run: |
          dnf install -y \
          xorriso \
          rpm \
          limine \
          systemd \
          btrfs-progs \
          e2fsprogs \
          xfsprogs \
          dosfstools \
          grub2 \
          parted \
          util-linux-core \
          systemd-container \
          grub2-efi \
          uboot-images-armv8 \
          uboot-tools \
          rustc \
          qemu-user-static-aarch64 \
          qemu-user-binfmt \
          qemu-kvm \
          qemu-img \
          cargo \
          moby-engine

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: Swatinem/rust-cache@v2

      - name: Build and install katsu
        run: |
          cargo install --path . --debug
      - name: Prepare loop devices
        run: |
          for i in $(seq 0 23);
          do
              sudo mknod -m 0660 /dev/loop$i b 7 0  2> /dev/null || true
          done
      - name: Run test
        run: |
          export PATH=$HOME/.cargo/bin:$PATH
          export KATSU_LOG=trace
          pushd tests
          COLORBT_SHOW_HIDDEN=1 katsu katsudon-arm.yaml 2>&1
          popd
