name: Continuous Integration

on:
  push:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f38
      # Pass /dev from host to container
      # Very hacky, but it works
      # Microsoft/Github, if you're reading this,
      # I'm sorry.
      options: --privileged -v /dev:/dev

    steps:
      - uses: actions/checkout@v4
      - name: Cache DNF packages
        uses: actions/cache@v2
        with:
          path: /var/cache/dnf
          key: dnf-${{ runner.os }}
          restore-keys: |
            dnf-${{ runner.os }}-
            dnf-

      - name: Install dependencies
        run: |
          dnf install -y \
          xorriso \
          rpm \
          limine \
          systemd \
          btrfs-progs \
          e2fsprogs \
          xfsprogs \
          dosfstools \
          grub2 \
          parted \
          util-linux-core \
          systemd-container \
          grub2-efi \
          uboot-images-armv8 \
          uboot-tools \
          rustc \
          qemu-user-static-aarch64 \
          qemu-user-binfmt \
          qemu-kvm \
          qemu-img \
          cargo \
          systemd-devel \
          mkpasswd \
          clang-devel \
          moby-engine

      - uses: Swatinem/rust-cache@v2

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test